# Site settings
title: Research Notes # type your own lablog title here

description: > # this means to ignore newlines until "baseurl:"
baseurl: "/researchNotes" # the subpath of your site, e.g. /blog/
url: "https://watsonryan.github.io" # the base hostname & protocol for your site
include: [ _assets , _projects ]

name : Ryan Watson
email : rwatso12@gmail.com  
github_username: watsonryan
twitter_username:
website : git@github.com:watsonryan/researchNotes.git

# Build settings
markdown: kramdown
kramdown:
  input: GFM

noindex: true # if true, google will ignore your pages!

defaults:   # overwrite with in YAML frontmatter, e.g. 'place: New York'
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "post"
      place:  # default Geolocation of posts.
      author: # default author for posts (for multi-authoring)
